name: uoc20221pec3
channels:
  - defaults
  - conda-forge
dependencies:
  - dtreeviz=1.4.0
  - graphviz=0.20.1
  - jupyter=1.0.0
  - matplotlib=3.6.2
  - nltk=3.7
  - numpy=1.21.2
  - pandas=1.4.1
  - pydotplus=2.0.2
  - python=3.9.7
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - umap-learn=0.5.1
